### ISSUE TITLE
Error in folders

### ISSUE THREAD

**Issue by qgustavor** [qgustavor/mega#22]
For some reason some folders are failing to load. Error stacks:

```
TypeError: Cannot read property 'children' of undefined
---------------------------------
    at https://directme.ga/sw.js:4:8949
          var folder = nodes.find(function (node) {
                            ^
TypeError: Cannot read property 'find' of undefined
    at ...\main.node-cjs.js:1230:29
```

More information at: https://rollbar.com/qgustavor/Direct-MEGA/items/20/

**Edit:** there are two issues:

* MEGA is sending ~~corrupted data~~ gzipped data to the Node client (probably because the response is too large)
* ~~There are orphan files in the requested folder: [`filesMap[file.p] === undefined`](https://github.com/qgustavor/mega/blob/4e96241b6c16bf404e3d606612ea77068a5c1a19/lib/file.js#L99)~~  
Sorting folders before files don't work when there are nested folders.

**Comment by qgustavor** [comment]
Fixed in 2a245fe

**Comment by qgustavor** [comment]
For some reason it's still failing in some cases.

**Comment by qgustavor** [comment]
Folders with too many subfolders are still failing.
